version: "3"
services:
    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: micro-admin
            MONGO_INITDB_ROOT_PASSWORD: rootMicroAdmin
        ports:
            - 27017:27017
        volumes:
            - mongodb_data_micro_admin:/data/db
volumes:
    mongodb_data_micro_admin: