version: "3"
services:
    mongodb_container:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: micro-ranking
            MONGO_INITDB_ROOT_PASSWORD: rootMicroRanking
        command: mongod --port 27019
        ports:
            - 27019:27019
        volumes:
            - mongodb_data_micro_challenges:/data/db
volumes:
    rabbitmq_data:
    mongodb_data_micro_challenges: